//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.UIMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        internal static string Banned {
            get {
                return ResourceManager.GetString("Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        internal static string BannedNormalizedPassword {
            get {
                return ResourceManager.GetString("BannedNormalizedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        internal static string BannedNormalizedWord {
            get {
                return ResourceManager.GetString("BannedNormalizedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated successfully..
        /// </summary>
        internal static string ChangeSuccessful {
            get {
                return ResourceManager.GetString("ChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not meet the complexity requirements..
        /// </summary>
        internal static string ComplexityPointsNotMet {
            get {
                return ResourceManager.GetString("ComplexityPointsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not meet the complexity requirements..
        /// </summary>
        internal static string ComplexityThresholdNotMet {
            get {
                return ResourceManager.GetString("ComplexityThresholdNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        internal static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password.
        /// </summary>
        internal static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot contain your username..
        /// </summary>
        internal static string ContainsAccountName {
            get {
                return ResourceManager.GetString("ContainsAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot contain any part of your name..
        /// </summary>
        internal static string ContainsFullName {
            get {
                return ResourceManager.GetString("ContainsFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        internal static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your current password.
        /// </summary>
        internal static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not match the approval criteria..
        /// </summary>
        internal static string DidNotMatchApprovalRegex {
            get {
                return ResourceManager.GetString("DidNotMatchApprovalRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        internal static string FilterError {
            get {
                return ResourceManager.GetString("FilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        internal static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You existing username or password is incorrect..
        /// </summary>
        internal static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is not long enough..
        /// </summary>
        internal static string LengthRequirementsNotMet {
            get {
                return ResourceManager.GetString("LengthRequirementsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was explicitly rejected according to the complexity requirements..
        /// </summary>
        internal static string MatchedRejectRegex {
            get {
                return ResourceManager.GetString("MatchedRejectRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        internal static string NewPasswordIsRequired {
            get {
                return ResourceManager.GetString("NewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password does not meet the complexity requirements. Please review the instructions above try again..
        /// </summary>
        internal static string PasswordDoesNotMeetPolicy {
            get {
                return ResourceManager.GetString("PasswordDoesNotMeetPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password has been seen in {0} data breaches. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        internal static string PasswordIsPwned {
            get {
                return ResourceManager.GetString("PasswordIsPwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password has been seen in {0} data breaches. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        internal static string PasswordPwned {
            get {
                return ResourceManager.GetString("PasswordPwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new passwords do not match..
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be blank..
        /// </summary>
        internal static string PasswordWasBlank {
            get {
                return ResourceManager.GetString("PasswordWasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResultApproved {
            get {
                return ResourceManager.GetString("ResultApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        internal static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank..
        /// </summary>
        internal static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
    }
}
