//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lithnet.ActiveDirectory.PasswordChange.Web.App_LocalResources.UIMessages", typeof(UIMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        public static string BannedNormalizedWord {
            get {
                return ResourceManager.GetString("BannedNormalizedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated successfully..
        /// </summary>
        public static string ChangeSuccessful {
            get {
                return ResourceManager.GetString("ChangeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not meet the complexity requirements..
        /// </summary>
        public static string ComplexityPointsNotMet {
            get {
                return ResourceManager.GetString("ComplexityPointsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not meet the complexity requirements..
        /// </summary>
        public static string ComplexityThresholdNotMet {
            get {
                return ResourceManager.GetString("ComplexityThresholdNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        public static string Compromised {
            get {
                return ResourceManager.GetString("Compromised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This password has been found in a data breach and could be used to hack your account. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        public static string CompromisedNormalizedPassword {
            get {
                return ResourceManager.GetString("CompromisedNormalizedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password.
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot contain your username..
        /// </summary>
        public static string ContainsAccountName {
            get {
                return ResourceManager.GetString("ContainsAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot contain any part of your name..
        /// </summary>
        public static string ContainsFullName {
            get {
                return ResourceManager.GetString("ContainsFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your current password.
        /// </summary>
        public static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password did not match the approval criteria..
        /// </summary>
        public static string DidNotMatchApprovalRegex {
            get {
                return ResourceManager.GetString("DidNotMatchApprovalRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        public static string FilterError {
            get {
                return ResourceManager.GetString("FilterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your existing username or password is incorrect..
        /// </summary>
        public static string InvalidUserOrPassword {
            get {
                return ResourceManager.GetString("InvalidUserOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is not long enough..
        /// </summary>
        public static string LengthRequirementsNotMet {
            get {
                return ResourceManager.GetString("LengthRequirementsNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was explicitly rejected according to the complexity requirements..
        /// </summary>
        public static string MatchedRejectRegex {
            get {
                return ResourceManager.GetString("MatchedRejectRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your new password.
        /// </summary>
        public static string NewPasswordIsRequired {
            get {
                return ResourceManager.GetString("NewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password has been seen in {0} data breaches. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        public static string PasswordIsPwned {
            get {
                return ResourceManager.GetString("PasswordIsPwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password has been seen in {0} data breaches. It is not safe to use here or on any other accounts you may have..
        /// </summary>
        public static string PasswordPwned {
            get {
                return ResourceManager.GetString("PasswordPwned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That password has either been used before, or you&apos;ve tried to change your password more than once in a 24 hour period..
        /// </summary>
        public static string PasswordRejectedByAdPolicy {
            get {
                return ResourceManager.GetString("PasswordRejectedByAdPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new passwords do not match..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password cannot be blank..
        /// </summary>
        public static string PasswordWasBlank {
            get {
                return ResourceManager.GetString("PasswordWasBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please contact your service desk for support..
        /// </summary>
        public static string UnhandledError {
            get {
                return ResourceManager.GetString("UnhandledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be blank..
        /// </summary>
        public static string UserNameIsRequired {
            get {
                return ResourceManager.GetString("UserNameIsRequired", resourceCulture);
            }
        }
    }
}
